import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lxbox/services/wireguard/masquerade_source.dart';
import 'package:lxbox/widgets/masquerade_fields.dart';

/// §623 (ревизия 1) — секция Masquerade вкладки Settings узла
/// WireGuard/AmneziaWG: строки как у Detour, выбор пишется сразу. Запись в
/// источник проверяет `masquerade_source_test.dart`; здесь — только виджет,
/// без экрана узла и без моста к ядру.
void main() {
  final written = <Masquerade>[];
  var dirtyTaps = 0;

  Future<void> pump(
    WidgetTester tester, {
    Masquerade value = Masquerade.off,
    String? reason,
    bool sipBlocked = false,
    bool sourceDirty = false,
    String Function()? randomDomain,
    List<String> pool = const [],
  }) async {
    written.clear();
    dirtyTaps = 0;
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: SingleChildScrollView(
            child: MasqueradeSection(
              value: value,
              unavailableReason: reason,
              sipBlocked: sipBlocked,
              sourceDirty: sourceDirty,
              onSourceDirty: () => dirtyTaps++,
              randomDomain: randomDomain,
              domainPool: pool,
              onChanged: (m) async => written.add(m),
            ),
          ),
        ),
      ),
    );
  }

  final protocolRow = find.byKey(const ValueKey('masquerade-protocol'));
  final domainRow = find.byKey(const ValueKey('masquerade-domain'));
  final browserRow = find.byKey(const ValueKey('masquerade-browser'));

  Future<void> tapAndSettle(WidgetTester tester, Finder f) async {
    await tester.tap(f);
    await tester.pumpAndSettle();
  }

  testWidgets('no Save button; rows follow the protocol', (tester) async {
    await pump(tester);
    expect(find.byType(FilledButton), findsNothing);
    expect(find.text('Save'), findsNothing);
    expect(protocolRow, findsOneWidget);
    expect(domainRow, findsNothing);
    expect(browserRow, findsNothing);

    await pump(
      tester,
      value: const Masquerade(ip: 'quic', id: 'a.example', ib: 'chrome'),
    );
    expect(domainRow, findsOneWidget);
    expect(browserRow, findsOneWidget);
    expect(find.text('a.example'), findsOneWidget);

    await pump(tester, value: const Masquerade(ip: 'dns'));
    expect(domainRow, findsOneWidget);
    expect(browserRow, findsNothing);
    expect(find.text('Generated by the core'), findsOneWidget);

    await pump(tester, value: const Masquerade(ip: 'stun'));
    expect(domainRow, findsNothing);
    expect(browserRow, findsNothing);
  });

  testWidgets('explicit i1: rows disabled, reason shown', (tester) async {
    await pump(tester, reason: 'I1 wins');
    expect(find.text('I1 wins'), findsOneWidget);
    expect(tester.widget<ListTile>(protocolRow).enabled, isFalse);
    await tester.tap(protocolRow);
    await tester.pumpAndSettle();
    expect(find.byType(SimpleDialog), findsNothing);
  });

  testWidgets('i2 set: SIP is disabled in the dialog', (tester) async {
    await pump(tester, sipBlocked: true);
    await tapAndSettle(tester, protocolRow);
    final sip = tester.widget<RadioListTile<String>>(
      find.byKey(const ValueKey('masquerade-option-sip')),
    );
    expect(sip.enabled, isFalse);
    expect(
      find.text('Not available: the node sets I2 explicitly.'),
      findsOneWidget,
    );
    final dns = tester.widget<RadioListTile<String>>(
      find.byKey(const ValueKey('masquerade-option-dns')),
    );
    expect(dns.enabled, isNot(false));
  });

  Finder domainInput() => find.descendant(
    of: find.byKey(const ValueKey('masquerade-domain-input')),
    matching: find.byType(TextField),
  );

  Future<void> pickProtocol(WidgetTester tester, String v) async {
    await tapAndSettle(tester, protocolRow);
    await tapAndSettle(tester, find.byKey(ValueKey('masquerade-option-$v')));
  }

  testWidgets('QUIC: random pool domain and Chrome, written at once', (
    tester,
  ) async {
    await pump(tester, randomDomain: () => 'pool.example');
    await pickProtocol(tester, 'quic');
    expect(written, [
      const Masquerade(ip: 'quic', id: 'pool.example', ib: 'chrome'),
    ]);
  });

  testWidgets('DNS: an empty domain gets a random one', (tester) async {
    await pump(tester, randomDomain: () => 'pool.example');
    await pickProtocol(tester, 'dns');
    expect(written, [const Masquerade(ip: 'dns', id: 'pool.example')]);
  });

  testWidgets('empty pool: the domain dialog opens before the write', (
    tester,
  ) async {
    await pump(tester, randomDomain: () => '');
    await pickProtocol(tester, 'quic');
    expect(written, isEmpty);
    expect(find.byType(AlertDialog), findsOneWidget);
    await tester.enterText(domainInput(), 'own.example');
    await tester.pump();
    await tapAndSettle(
      tester,
      find.byKey(const ValueKey('masquerade-domain-ok')),
    );
    expect(written, [
      const Masquerade(ip: 'quic', id: 'own.example', ib: 'chrome'),
    ]);
  });

  testWidgets('domain field: the arrow opens the whole pool without typing, '
      'an entry and the dice set the field', (tester) async {
    await pump(
      tester,
      value: const Masquerade(ip: 'quic', id: 'zzz.example'),
      pool: const ['a.example', 'b.example', 'c.example'],
      randomDomain: () => 'b.example',
    );
    await tapAndSettle(tester, domainRow);
    expect(find.byType(MenuItemButton), findsNothing);

    // Текст не совпадает ни с одним пунктом — меню всё равно целое.
    await tapAndSettle(
      tester,
      find.byKey(const ValueKey('masquerade-domain-arrow')),
    );
    expect(find.byType(MenuItemButton), findsNWidgets(3));
    await tapAndSettle(
      tester,
      find.widgetWithText(MenuItemButton, 'c.example'),
    );
    expect(
      tester.widget<TextField>(domainInput()).controller!.text,
      'c.example',
    );

    await tapAndSettle(
      tester,
      find.byKey(const ValueKey('masquerade-domain-dice')),
    );
    expect(
      tester.widget<TextField>(domainInput()).controller!.text,
      'b.example',
    );

    await tapAndSettle(
      tester,
      find.byKey(const ValueKey('masquerade-domain-ok')),
    );
    expect(written, [const Masquerade(ip: 'quic', id: 'b.example')]);
  });

  testWidgets('domain dialog does not let OK through on an error', (
    tester,
  ) async {
    await pump(
      tester,
      value: const Masquerade(ip: 'quic', id: 'a.example'),
    );
    await tapAndSettle(tester, domainRow);
    final input = domainInput();
    final ok = find.byKey(const ValueKey('masquerade-domain-ok'));

    await tester.enterText(input, 'bad domain');
    await tester.pump();
    expect(tester.widget<FilledButton>(ok).onPressed, isNull);
    expect(find.text('Not a valid domain name.'), findsOneWidget);

    await tester.enterText(input, '');
    await tester.pump();
    expect(tester.widget<FilledButton>(ok).onPressed, isNull);
    expect(find.text('Domain is required for QUIC.'), findsOneWidget);

    await tester.enterText(input, 'b.example');
    await tester.pump();
    await tapAndSettle(tester, ok);
    expect(written, [const Masquerade(ip: 'quic', id: 'b.example')]);
  });

  testWidgets('unsaved Source edit: tap opens nothing, owner is told', (
    tester,
  ) async {
    await pump(tester, sourceDirty: true);
    await tapAndSettle(tester, protocolRow);
    expect(find.byType(SimpleDialog), findsNothing);
    expect(dirtyTaps, 1);
    expect(written, isEmpty);
  });
}
